// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriPlan.Api.Data;

#nullable disable

namespace NutriPlan.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriPlan.Api.Models.DayPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("mealPlanId");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId", "Day")
                        .IsUnique();

                    b.ToTable("day_plans");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision")
                        .HasColumnName("calories");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision")
                        .HasColumnName("carbs");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision")
                        .HasColumnName("fat");

                    b.Property<double>("Fibers")
                        .HasColumnType("double precision")
                        .HasColumnName("fibers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Portion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("portion");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision")
                        .HasColumnName("protein");

                    b.HasKey("Id");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DayPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("dayPlanId");

                    b.Property<bool>("IsCheat")
                        .HasColumnType("boolean")
                        .HasColumnName("isCheat");

                    b.Property<Guid>("MealSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("mealSlotId");

                    b.HasKey("Id");

                    b.HasIndex("MealSlotId");

                    b.HasIndex("DayPlanId", "MealSlotId")
                        .IsUnique();

                    b.ToTable("meals");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("foodId");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("mealId");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId", "FoodId")
                        .IsUnique();

                    b.ToTable("meal_foods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("integer")
                        .HasColumnName("dailyCalories");

                    b.Property<int?>("DailyCarbs")
                        .HasColumnType("integer")
                        .HasColumnName("dailyCarbs");

                    b.Property<int?>("DailyFat")
                        .HasColumnType("integer")
                        .HasColumnName("dailyFat");

                    b.Property<int?>("DailyProtein")
                        .HasColumnType("integer")
                        .HasColumnName("dailyProtein");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("meal_plans");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("mealPlanId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.Property<string>("Time")
                        .HasColumnType("text")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("meal_slots");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.PresetMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("preset_meals");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.PresetMealFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("foodId");

                    b.Property<Guid>("PresetMealId")
                        .HasColumnType("uuid")
                        .HasColumnName("presetMealId");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("PresetMealId", "FoodId")
                        .IsUnique();

                    b.ToTable("preset_meal_foods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("InviteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inviteExpiresAt");

                    b.Property<string>("InviteToken")
                        .HasColumnType("text")
                        .HasColumnName("inviteToken");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ownerId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("InviteToken")
                        .IsUnique()
                        .HasFilter("\"inviteToken\" IS NOT NULL");

                    b.HasIndex("OwnerId");

                    b.ToTable("shopping_lists");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.ShoppingListMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("mealId");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shoppingListId");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("ShoppingListId", "MealId")
                        .IsUnique();

                    b.ToTable("shopping_list_meals");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.ShoppingListMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joinedAt");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shoppingListId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ShoppingListId", "UserId")
                        .IsUnique();

                    b.ToTable("shopping_list_members");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("googleId");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("isAdmin");

                    b.Property<Guid?>("MainMealPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("mainMealPlanId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("\"googleId\" IS NOT NULL");

                    b.HasIndex("MainMealPlanId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.DayPlan", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.MealPlan", "MealPlan")
                        .WithMany("Days")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Meal", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.DayPlan", "DayPlan")
                        .WithMany("Meals")
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriPlan.Api.Models.MealSlot", "MealSlot")
                        .WithMany("Meals")
                        .HasForeignKey("MealSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayPlan");

                    b.Navigation("MealSlot");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealFood", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.Food", "Food")
                        .WithMany("MealFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriPlan.Api.Models.Meal", "Meal")
                        .WithMany("Foods")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealPlan", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealSlot", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.MealPlan", "MealPlan")
                        .WithMany("Slots")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.PresetMeal", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.User", "User")
                        .WithMany("PresetMeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.PresetMealFood", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.Food", "Food")
                        .WithMany("PresetMealFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriPlan.Api.Models.PresetMeal", "PresetMeal")
                        .WithMany("Foods")
                        .HasForeignKey("PresetMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("PresetMeal");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.ShoppingList", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.ShoppingListMeal", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriPlan.Api.Models.ShoppingList", "ShoppingList")
                        .WithMany("Meals")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.ShoppingListMember", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.ShoppingList", "ShoppingList")
                        .WithMany("Members")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriPlan.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.User", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.MealPlan", "MainMealPlan")
                        .WithOne()
                        .HasForeignKey("NutriPlan.Api.Models.User", "MainMealPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MainMealPlan");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.DayPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Food", b =>
                {
                    b.Navigation("MealFoods");

                    b.Navigation("PresetMealFoods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Meal", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealPlan", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealSlot", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.PresetMeal", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.ShoppingList", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.User", b =>
                {
                    b.Navigation("MealPlans");

                    b.Navigation("PresetMeals");
                });
#pragma warning restore 612, 618
        }
    }
}
