// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriPlan.Api.Data;

#nullable disable

namespace NutriPlan.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriPlan.Api.Models.DayPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("mealPlanId");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId", "Day")
                        .IsUnique();

                    b.ToTable("day_plans");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision")
                        .HasColumnName("calories");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision")
                        .HasColumnName("carbs");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision")
                        .HasColumnName("fat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Portion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("portion");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision")
                        .HasColumnName("protein");

                    b.HasKey("Id");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DayPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("dayPlanId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Time")
                        .HasColumnType("text")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("DayPlanId");

                    b.ToTable("meals");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("foodId");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("mealId");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId", "FoodId")
                        .IsUnique();

                    b.ToTable("meal_foods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("integer")
                        .HasColumnName("dailyCalories");

                    b.Property<int?>("DailyCarbs")
                        .HasColumnType("integer")
                        .HasColumnName("dailyCarbs");

                    b.Property<int?>("DailyFat")
                        .HasColumnType("integer")
                        .HasColumnName("dailyFat");

                    b.Property<int?>("DailyProtein")
                        .HasColumnType("integer")
                        .HasColumnName("dailyProtein");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("meal_plans");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("googleId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("\"googleId\" IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.DayPlan", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.MealPlan", "MealPlan")
                        .WithMany("Days")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Meal", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.DayPlan", "DayPlan")
                        .WithMany("Meals")
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayPlan");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealFood", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.Food", "Food")
                        .WithMany("MealFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriPlan.Api.Models.Meal", "Meal")
                        .WithMany("Foods")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealPlan", b =>
                {
                    b.HasOne("NutriPlan.Api.Models.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.DayPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Food", b =>
                {
                    b.Navigation("MealFoods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.Meal", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.MealPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("NutriPlan.Api.Models.User", b =>
                {
                    b.Navigation("MealPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
